In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [20]:
# efficient matrix multiplication w/ masking

a = torch.ones(3, 3)
print(a)

a = a.tril()
print(a)

a = a / a.sum(1, keepdim=True)
print(a)

b = torch.randint(0, 10, (3, 3)).float()
print(b)

c = a @ b
print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])
tensor(6.)
tensor([1., 2., 3.])
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
tensor([[3., 1., 4.],
        [2., 9., 9.],
        [5., 5., 3.]])
tensor([[3.0000, 1.0000, 4.0000],
        [2.5000, 5.0000, 6.5000],
        [3.3333, 5.0000, 5.3333]])
